variable "external_id" {
  description = "External ID generated by Opsima to secure the trust policy of the Opsima role. Do not change."
  type        = string
  sensitive   = true

  validation {
    condition     = can(regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$", var.external_id))
    error_message = "external_id must be a UUID."
  }
}

variable "opsima_principal" {
  description = "Opsima AWS account ID allowed to assume the Opsima role. Do not change."
  type        = string
  default     = "539247457822"

  validation {
    condition     = can(regex("^[0-9]{12}$", var.opsima_principal))
    error_message = "opsima_principal must be a 12-digit AWS account ID."
  }
}

variable "customer_short_id" {
  description = "Short ID generated by Opsima for your organization. Used to name the CUR bucket and the Opsima OU. Do not change."
  type        = string

  validation {
    condition     = can(regex("^[0-9a-fA-F]{10}$", var.customer_short_id))
    error_message = "customer_short_id must be 10 hexadecimal characters."
  }
}

variable "organization_id" {
  description = "ID of your AWS Organization (o-xxxxxxxxxx)."
  type        = string

  validation {
    condition     = can(regex("^o-[a-z0-9]{10}$", var.organization_id))
    error_message = "organization_id must look like o-xxxxxxxxxx."
  }
}

variable "organization_root_id" {
  description = "ID of the root of your AWS Organization (r-xxxx)."
  type        = string

  validation {
    condition     = can(regex("^r-[a-z0-9]{4,32}$", var.organization_root_id))
    error_message = "organization_root_id must look like r-xxxx."
  }
}

variable "create_cur_bucket" {
  description = "Whether to create the S3 bucket receiving the Cost and Usage Report."
  type        = bool
  default     = true
}

variable "create_opsima_organizational_unit" {
  description = "Whether to create the Organizational Unit hosting Opsima accounts. Ignored when opsima_organizational_unit_id is set."
  type        = bool
  default     = true
}

variable "opsima_organizational_unit_id" {
  description = "ID of an existing Organizational Unit hosting Opsima accounts. Leave empty to let the module create one."
  type        = string
  default     = ""

  validation {
    condition     = var.opsima_organizational_unit_id == "" || can(regex("^ou-[a-z0-9]{4,32}-[a-z0-9]{8,32}$", var.opsima_organizational_unit_id))
    error_message = "opsima_organizational_unit_id must be empty or look like ou-xxxx-xxxxxxxx."
  }
}
